/**
 * What `Evidence.content` holds — it depends on the evidence type.
 *
 * There is one column but three meanings, which is why wiring the UI
 * straight at `content` is not safe on its own:
 *
 *   - TEXT → the user's note body. Prose. Editable.
 *   - LINK → the target URL. Editable, but rendered as a link.
 *   - FILE → the object-storage **pathKey**, written by the upload and
 *     by `replaceEvidenceFile` (`content: pathKey`). It is an internal
 *     pointer: showing it to a user leaks a storage path, and letting an
 *     edit form write it would detach the row from its file.
 *
 * The same split applies to evidence generated by the posture/scanner
 * writers, which also claim `content`.
 *
 * Every surface that reads or writes `content` should ask this module
 * what role the field plays for that row rather than assuming prose.
 */

/** How `content` should be treated for a given evidence type. */
export type EvidenceContentRole = 'note' | 'url' | 'internal';

export function evidenceContentRole(type: string | null | undefined): EvidenceContentRole {
    switch (type) {
        case 'TEXT':
            return 'note';
        case 'LINK':
            return 'url';
        // FILE — and anything unrecognised. Defaulting unknown types to
        // `internal` is the safe direction: a new evidence type is
        // hidden and read-only until someone decides otherwise, rather
        // than leaking whatever its writer put in `content`.
        default:
            return 'internal';
    }
}

/**
 * True when a user may edit `content` for this evidence type. Guards the
 * edit form AND the usecase — the API is public, so the client-side gate
 * alone would not stop a hand-rolled PUT from wiping a FILE's pathKey.
 */
export function isEvidenceContentEditable(type: string | null | undefined): boolean {
    return evidenceContentRole(type) !== 'internal';
}
