/**
 * GET /api/docs — Swagger UI for the OpenAPI 3.1 spec.
 *
 * GAP-10 step 4. Renders the interactive API documentation in
 * non-production environments, fetching the spec from `/openapi.json`
 * (served statically from `public/openapi.json`, generated by
 * `npm run openapi:generate`).
 *
 * Production exposure model (PATH A — deliberate): HARD 404 in
 * production. The interactive reference is a dev/staging convenience;
 * the public-facing, production-served artefact is the static
 * `/openapi.json` (machine-readable spec). Partners render it in their
 * own Swagger UI / Postman / curl, or generate a client from it. Two
 * layers of defense back the 404 — (1) the handler short-circuits
 * before producing any HTML; (2) the route is in the read-rate-limit
 * exclusion list (`apiReadRateLimit.ts`), sized for monitoring traffic,
 * so even a config drift that re-enabled it in production would limit
 * blast radius. The interactive HTML reveals every endpoint shape at a
 * single GET — fine for partners on staging, extra fingerprinting
 * surface in production. See `docs/api-consumer-guide.md` for the
 * dev/staging-vs-production split.
 *
 * Swagger UI assets are SELF-HOSTED (no CDN):
 *   - `public/swagger-ui/` carries the three pinned `swagger-ui-dist`
 *     assets, COMMITTED to the repo (re-vendor with
 *     `npm run swagger-ui:vendor` → `scripts/copy-swagger-ui.js` after
 *     bumping the dep). Committed rather than install-generated because
 *     `postinstall` is pinned to exactly `patch-package`.
 *   - This kills the CSP problem (`'self'` is enough — no jsdelivr
 *     allowance), the supply-chain surface (assets are pinned to the
 *     locked dependency, not whatever the CDN serves), and the
 *     air-gapped-staging problem (no egress required).
 *   - Cost: ~1.8 MB in `public/`, served through Next.js's static-asset
 *     pipeline.
 */
import { NextResponse } from 'next/server';
import { withApiErrorHandling } from '@/lib/errors/api';

// Pinned to the `swagger-ui-dist` devDependency version. The assets are
// served from `/swagger-ui/` (vendored into public/ by postinstall),
// NOT from a CDN — keep this in sync with package.json if bumped.
const SWAGGER_CSS = '/swagger-ui/swagger-ui.css';
const SWAGGER_JS = '/swagger-ui/swagger-ui-bundle.js';
const SWAGGER_PRESET_JS = '/swagger-ui/swagger-ui-standalone-preset.js';

/**
 * True when the docs route is allowed to render HTML.
 *
 *   - Production: false. Always 404.
 *   - Test: false. The route only exists for interactive use.
 *   - Development + staging: true.
 *
 * Operators who genuinely need the docs in a production-like
 * environment (e.g. for partner SDK debugging) should hit the
 * staging deploy where it's enabled.
 */
function isDocsEnabled(): boolean {
    const nodeEnv = process.env.NODE_ENV;
    if (nodeEnv === 'production') return false;
    if (nodeEnv === 'test') return false;
    return true;
}

// Epic E — wrapped for x-request-id + standardized error contract.
// Never throws in normal operation; an unexpected runtime error in
// the HTML build path is now reported as a clean 5xx ApiErrorResponse
// instead of a Next.js stack-trace page.
export const GET = withApiErrorHandling(async (): Promise<NextResponse> => {
    if (!isDocsEnabled()) {
        // Match Next.js's default 404 shape so this route is
        // indistinguishable from a route that never existed.
        return new NextResponse('Not Found', {
            status: 404,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    }

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex, nofollow" />
  <title>Inflect Compliance API — interactive docs</title>
  <link rel="stylesheet" href="${SWAGGER_CSS}" />
  <style>
    body { margin: 0; }
    .topbar { display: none; }
    /* Distinguish dev/staging visually so a screenshot is unambiguous. */
    body::before {
      content: "DEVELOPMENT — interactive API docs";
      display: block;
      background: #fbbf24;
      color: #1f2937;
      padding: 6px 16px;
      font: 600 12px/1.4 ui-sans-serif, system-ui, sans-serif;
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="${SWAGGER_JS}"></script>
  <script src="${SWAGGER_PRESET_JS}"></script>
  <script>
    window.addEventListener('load', function () {
      window.ui = SwaggerUIBundle({
        url: '/openapi.json',
        dom_id: '#swagger-ui',
        deepLinking: true,
        layout: 'BaseLayout',
        // Keep the Authorize credential across reloads so a tester
        // pastes their API key / signs in once per session.
        persistAuthorization: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset,
        ],
      });
    });
  </script>
</body>
</html>
`;

    return new NextResponse(html, {
        status: 200,
        headers: {
            'Content-Type': 'text/html; charset=utf-8',
            // Belt-and-braces: even though isDocsEnabled() blocks
            // production rendering, the response itself signals to
            // any cache that this is a dev-only document.
            'Cache-Control': 'no-store',
            'X-Robots-Tag': 'noindex, nofollow',
        },
    });
});
