/**
 * GAP-10 step 4 — Swagger UI route gating.
 *
 * Verifies that GET /api/docs is dev/staging only — production must
 * always 404, and a CSP/cache-header drift is caught.
 *
 * The actual rendering of Swagger UI happens in the browser, loading
 * SELF-HOSTED assets from `/swagger-ui/` (vendored from
 * `swagger-ui-dist` by `scripts/copy-swagger-ui.js` at install time —
 * no CDN). This test only validates the server-side gate + response
 * shape, not the JavaScript that swagger-ui-bundle ships.
 */


const { NextRequest } = require('next/server');

function loadRouteFresh() {
    jest.resetModules();

    return require('@/app/api/docs/route');
}

// Epic E — the route is now wrapped with `withApiErrorHandling`,
// which expects a real NextRequest (it reads `req.headers`,
// `req.nextUrl.pathname`, `req.method`). The route handler itself
// still ignores the request, so a stub URL is sufficient.
function fakeRequest() {
    return new NextRequest('http://localhost/api/docs', { method: 'GET' });
}

describe('GET /api/docs — Swagger UI gating', () => {
    const originalEnv = process.env;

    beforeEach(() => {
        process.env = { ...originalEnv };
    });

    afterAll(() => {
        process.env = originalEnv;
    });

    it('returns 404 in production', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'production';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});

        expect(res.status).toBe(404);
        const body = await res.text();
        // Body must not leak any HTML or hint that the route exists —
        // indistinguishable from a route that never existed.
        expect(body).toBe('Not Found');
        expect(body).not.toMatch(/Swagger|swagger|openapi/i);
    });

    it('returns 404 in test (no interactive use during Jest runs)', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'test';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        expect(res.status).toBe(404);
    });

    it('returns 200 + HTML in development', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(res.status).toBe(200);
        expect(res.headers.get('Content-Type')).toMatch(/text\/html/);
        expect(body).toMatch(/<!DOCTYPE html>/);
        // Page loads the spec from /openapi.json (the static file
        // generated by `npm run openapi:generate`).
        expect(body).toContain("url: '/openapi.json'");
    });

    it('serves Swagger UI assets self-hosted from /swagger-ui/ (no CDN)', async () => {
        // Self-hosting kills the CSP / supply-chain / air-gap problems.
        // A regression back to a cdn.jsdelivr.net URL would reintroduce
        // all three. Assets are vendored by scripts/copy-swagger-ui.js.
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(body).toContain('/swagger-ui/swagger-ui.css');
        expect(body).toContain('/swagger-ui/swagger-ui-bundle.js');
        expect(body).toContain('/swagger-ui/swagger-ui-standalone-preset.js');
        // Plain substring check (not a regex) — host presence = CDN regression.
        expect(body.includes('cdn.jsdelivr.net')).toBe(false);
    });

    it('declares an Authorize flow (persistAuthorization) for "Try it out"', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(body).toContain('persistAuthorization: true');
    });

    it('sets dev-friendly cache + robot headers', async () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});

        expect(res.headers.get('Cache-Control')).toBe('no-store');
        expect(res.headers.get('X-Robots-Tag')).toMatch(/noindex/);
    });

    it('emits a visual DEVELOPMENT banner so screenshots are unambiguous', async () => {
        // Operator-debugging hygiene — a screenshot of the docs page
        // taken from a contributor's machine should make it obvious
        // this isn't production. Removing the banner is a regression.
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development';
        const { GET } = loadRouteFresh();

        const res = await GET(fakeRequest(), {});
        const body = await res.text();

        expect(body).toMatch(/DEVELOPMENT/);
    });
});
